.github/workflows/firebase-hosting-deploy.yml
name: Firebase Hosting CD

on:
  push:
    branches:
      - main  # Ustaw gałąź, która ma wyzwalać wdrożenie

jobs:
  build_and_deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    
    steps:
      - name: Sprawdzenie kodu z repozytorium
        uses: actions/checkout@v4

      - name: Ustawienie Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Zalecana stabilna wersja Node.js

      - name: Instalacja Firebase CLI
        run: npm install -g firebase-tools

      - name: Wdrożenie na Firebase Hosting
        # Używamy --token z GitHub Secrets
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
        env:
          # Konieczne, by akcja wiedziała, że to jest CI/CD
          FIREBASE_CLI_PREVIEWS: hostingchannels
